/** 英文字典（core 域）：key 为中文原文，value 为英文译文。 */
export const CORE_DICT: Record<string, string> = {
  // ── 语境消歧条目（tCtx 专用，key 形如 `中文#ctx`） ──
  '关闭#switch': 'Off',
  '退出#leave': 'Leave',
  '恢复#restore': 'Restore',
  '启用#state': 'Enabled',
  '创建#time': 'Created',
  '图片#unit': 'image ',
  'HugAgentOS AI 智能助手': 'HugAgentOS AI Assistant',
  'AI 智能助手': 'AI Assistant',
  '基于 AI 能力的场景化智能应用': 'AI-powered smart applications for business scenarios',
  '本平台生成内容由AI大模型生成，不构成任何建议；涉及业务决策请以权威信息为准。':
    'Content is generated by an AI model and does not constitute advice. Use authoritative sources for business decisions.',
  '系统托管': 'System-managed',
  // App.tsx — branding / fallbacks
  'HugAgentOS': 'HugAgentOS',
  '新对话': 'New Chat',
  '项目：': 'Project: ',
  '项目': 'Project',
  '对话': 'Chat',
  '计划模式': 'Plan Mode',

  // App.tsx — recommend banner
  '推荐用法：优先使用知识库检索可提升可引用性与结果可靠性。': 'Tip: Using Knowledge Base retrieval improves citability and result reliability.',
  '前往知识库 >': 'Go to Knowledge Base >',
  '关闭': 'Close',
  '打开侧边栏': 'Open sidebar',
  '关闭侧边栏': 'Close sidebar',

  // api.ts — upload error messages
  '文件过大，单个文件不能超过 {n} MB': 'File too large. Maximum file size is {n} MB.',
  '不支持的文件格式，仅支持：{allowed}': 'Unsupported file format. Allowed types: {allowed}.',
  '不支持的文件格式': 'Unsupported file format.',
  '上传失败 ({status})': 'Upload failed ({status}).',
  '上传失败：{status}': 'Upload failed: {status}.',
  '导出失败：{status}': 'Export failed: {status}.',
  '头像上传失败: {status}': 'Avatar upload failed: {status}.',
};
