"""Word document creation primitives.

These functions are intended to be called from a sandbox-side Python script
generated by ``mcp_servers/_office_shared/script_builder.py``. They write the
output ``.docx`` to ``engine.output_path(filename)`` so the
sandbox sidecar auto-collects the file.

Each function returns a small dict with metadata that the MCP tool surfaces
back to the LLM (e.g. file size, paragraph count). The actual file bytes
travel through the sandbox file-collection channel, not through ``data``.
"""
from __future__ import annotations

import io
import os
from typing import Any

from ._handle import input_path, output_path
from .styles import (
    apply_cjk_font_to_para,
    fonts_for_language,
    set_document_default_fonts,
    setup_heading_styles,
)


def _new_document(language: str = "zh"):
    """Create a python-docx Document with CJK fonts pre-configured."""
    from docx import Document

    doc = Document()
    body_font, heading_font = fonts_for_language(language)
    set_document_default_fonts(doc, body_font)
    setup_heading_styles(doc, heading_font)
    return doc


def create_document(
    *,
    filename: str,
    title: str = "",
    language: str = "zh",
) -> dict[str, Any]:
    """Create a new .docx with optional title heading and 方正 CJK fonts.

    Args:
        filename: output filename (relative to sandbox cwd; sidecar auto-collects)
        title: if non-empty, added as a top-level Title-styled paragraph
        language: ``zh`` (default, 方正 fonts) or ``en`` (Calibri fallback)

    Returns:
        ``{"output_filename": str, "title": str, "language": str,
           "size_bytes": int, "paragraph_count": int}``
    """
    body_font, _heading_font = fonts_for_language(language)
    doc = _new_document(language)

    if title:
        para = doc.add_heading(title, level=0)
        # heading style already configured by setup_heading_styles; ensure CJK applied to title runs
        apply_cjk_font_to_para(para, _heading_font)

    out = output_path(filename)
    out.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(out))

    size = out.stat().st_size
    return {
        "output_filename": filename,
        "title": title,
        "language": language,
        "size_bytes": size,
        "paragraph_count": len(doc.paragraphs),
    }


def add_heading(
    *,
    input_filename: str,
    output_filename: str,
    text: str,
    level: int = 1,
) -> dict[str, Any]:
    """Open ``input_filename``, append a heading, save as ``output_filename``."""
    from docx import Document

    if not (1 <= level <= 6):
        raise ValueError(f"level must be 1-6, got {level}")

    doc = Document(str(input_path(input_filename)))
    para = doc.add_heading(text, level=level)
    # Re-apply CJK so newly-added heading respects existing language choice.
    # We don't know which language the source was authored in; default to 方正
    # which is the dominant case for this project. English-only documents can
    # have set_document_default_fonts re-applied via a separate tool if needed.
    from .styles import HEADING_FONT
    apply_cjk_font_to_para(para, HEADING_FONT)

    out = output_path(output_filename)
    out.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(out))

    return {
        "output_filename": output_filename,
        "added_heading": text,
        "level": level,
        "paragraph_count": len(doc.paragraphs),
    }


def _parse_markdown_table(markdown: str) -> list[list[str]]:
    """Parse a single markdown table block into rows of cell strings.

    Strips a separator row (``|---|---|``) if present. Empty input returns ``[]``.
    """
    import re as _re

    rows: list[list[str]] = []
    for line in (markdown or "").splitlines():
        s = line.strip()
        if not (s.startswith("|") and s.endswith("|") and s.count("|") >= 2):
            continue
        cells = [c.strip() for c in s.strip("|").split("|")]
        non_empty = [c for c in cells if c]
        if non_empty and all(_re.match(r"^:?-+:?$", c) for c in non_empty):
            continue  # separator row
        rows.append(cells)
    return rows


from .styles import (
    ANCHOR_REQUIRED_POSITIONS as _ANCHOR_REQUIRED_POSITIONS,
    INSERT_POSITIONS as _VALID_TABLE_POSITIONS,
)


def _auto_vertical_merge_empty_cells(table, has_header: bool) -> int:
    """Merge runs of empty cells vertically with the non-empty cell above.

    LLMs often emit tables where the leading columns are populated only on
    the first row of each logical group and left empty on subsequent rows
    (intent: a merged cell spanning multiple data rows). Without this
    post-processing, those blanks render as standalone empty cells with full
    borders + alt-row shading — clean in Word, fragmented in LibreOffice→PDF.

    For each column (skipping any column where the caller already injected
    ``<w:vMerge>``), scan top-to-bottom: a non-empty cell followed by N≥1
    contiguous empty cells gets ``<w:vMerge w:val="restart"/>``; followers
    get ``<w:vMerge/>`` (no val = continue). Returns the number of merge
    groups created.
    """
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn

    rows = list(table.rows)
    if len(rows) < 2:
        return 0
    n_cols = max(len(r.cells) for r in rows)

    # Hoisted: precompute text-presence + existing-vMerge matrices once
    # (each cell would otherwise be inspected up to 3× by the run-scan).
    cells_grid: list[list[Any]] = [list(r.cells) for r in rows]
    has_text_grid = [
        [
            any((p.text or "").strip() for p in cells_grid[r][c].paragraphs)
            if c < len(cells_grid[r]) else False
            for c in range(n_cols)
        ]
        for r in range(len(rows))
    ]
    vmerge_existing_col = [
        any(
            c < len(cells_grid[r])
            and (cells_grid[r][c]._element.find(qn("w:tcPr")) is not None)
            and cells_grid[r][c]._element.find(qn("w:tcPr")).find(qn("w:vMerge")) is not None
            for r in range(len(rows))
        )
        for c in range(n_cols)
    ]

    def _set_vmerge(cell, val: str | None) -> None:
        tcPr = cell._element.get_or_add_tcPr()
        for ex in tcPr.findall(qn("w:vMerge")):
            tcPr.remove(ex)
        vm = OxmlElement("w:vMerge")
        if val is not None:
            vm.set(qn("w:val"), val)
        tcPr.append(vm)

    start_row = 1 if has_header else 0
    groups_created = 0
    for c in range(n_cols):
        if vmerge_existing_col[c]:
            continue
        i = start_row
        while i < len(rows):
            if c >= len(cells_grid[i]) or not has_text_grid[i][c]:
                i += 1
                continue
            j = i + 1
            while j < len(rows) and c < len(cells_grid[j]) and not has_text_grid[j][c]:
                j += 1
            if j - i > 1:
                _set_vmerge(cells_grid[i][c], "restart")
                for k in range(i + 1, j):
                    _set_vmerge(cells_grid[k][c], None)
                groups_created += 1
            i = j
    return groups_created


def _resolve_anchor_paragraph(doc, position: str, anchor):
    """Resolve ``anchor`` (str or int) → target body paragraph element for
    table-insertion. Mirrors the semantics of ``_op_insert_text`` so the
    LLM-facing position model stays consistent.

    Returns the body-paragraph element to anchor against. ``after_section``
    has different semantics (insert before the next sibling heading, or at
    body-end if none) and is handled by ``_resolve_after_section_target``;
    callers branch on ``position`` and pick the right helper.
    """
    body = list(doc.paragraphs)
    if position == "after_heading":
        for p in body:
            sty = p.style.name if p.style else ""
            if sty.startswith(("Title", "Heading")) and (anchor or "") in p.text:
                return p._element
        raise ValueError(f"no heading containing {anchor!r} found")

    if position in ("after_paragraph", "before_paragraph"):
        if isinstance(anchor, int):
            idx = anchor
        elif isinstance(anchor, str) and anchor.lstrip("-").isdigit():
            idx = int(anchor)
        elif isinstance(anchor, str):
            for i, p in enumerate(body):
                if anchor in p.text:
                    return p._element
            raise ValueError(f"no paragraph containing {anchor!r} found")
        else:
            raise ValueError(f"anchor must be int or str, got {type(anchor).__name__}")
        if not (0 <= idx < len(body)):
            raise ValueError(
                f"paragraph index {idx} out of range "
                f"(document has {len(body)} body paragraphs)"
            )
        return body[idx]._element

    raise ValueError(f"position {position!r} doesn't take a single-paragraph anchor")


def _resolve_after_section_target(doc, anchor) -> tuple[str, Any]:
    """Resolve "end of section anchored at ``anchor``" into ``(mode, sibling_el)``.

    - ``mode == "before"``: insert before ``sibling_el`` (the next paragraph
      styled Title/Heading at same or higher level than the anchor heading).
    - ``mode == "at_end"``: no follow-up heading found; the caller should
      append before ``<w:sectPr>`` (or at body end).
    """
    if not isinstance(anchor, str) or not anchor:
        raise ValueError("after_section requires a heading-text anchor")
    body = list(doc.paragraphs)
    heading_idx = -1
    heading_level = -1
    for i, p in enumerate(body):
        sty = p.style.name if p.style else ""
        if not (sty == "Title" or sty.startswith("Heading ")):
            continue
        if anchor in p.text:
            heading_idx = i
            if sty == "Title":
                heading_level = 0
            else:
                try:
                    heading_level = int(sty.split()[1])
                except (IndexError, ValueError):
                    heading_level = 99
            break
    if heading_idx < 0:
        raise ValueError(f"no heading containing {anchor!r} found")
    for j in range(heading_idx + 1, len(body)):
        sty = body[j].style.name if body[j].style else ""
        if sty == "Title":
            level = 0
        elif sty.startswith("Heading "):
            try:
                level = int(sty.split()[1])
            except (IndexError, ValueError):
                continue
        else:
            continue
        if level <= heading_level:
            return ("before", body[j]._element)
    return ("at_end", None)


def _add_table_to_doc(
    doc,
    *,
    rows: list[list[str]] | None = None,
    markdown: str | None = None,
    has_header: bool = True,
    caption: str | None = None,
    position: str,
    anchor=None,
    auto_merge_empty: bool = True,
) -> dict[str, Any]:
    """Insert a styled table into an OPEN ``Document`` (no file I/O).

    Used directly by ``apply_edits`` (op="add_table") so the table can be
    inserted as part of a larger atomic edit batch.

    ``position`` is required (no default; callers must pick a placement
    explicitly). Accepted values:

        - ``"end"``: append at end of body
        - ``"start"``: insert at the very top of body
        - ``"after_heading"``: insert immediately after the first heading whose
          text contains ``anchor``
        - ``"after_paragraph"``: insert after body paragraph at ``anchor`` (int
          index or text substring)
        - ``"before_paragraph"``: insert before body paragraph at ``anchor``

    ``caption``, when provided, becomes a styled paragraph immediately above
    the table at the chosen position.

    ``auto_merge_empty`` (default True): for each non-header column, runs of
    consecutive empty cells directly below a non-empty cell are merged
    vertically (OOXML ``<w:vMerge>``). Lets the LLM author "category once,
    blank rows below" tables without ending up with fragmented blank cells
    in the PDF render.
    """
    from .styles import (
        BODY_FONT,
        apply_cjk_font_to_para,
        style_table,
    )

    if position not in _VALID_TABLE_POSITIONS:
        raise ValueError(
            f"position must be one of {_VALID_TABLE_POSITIONS}, got {position!r}"
        )
    if position in _ANCHOR_REQUIRED_POSITIONS and anchor is None:
        raise ValueError(f"position={position!r} requires 'anchor'")

    if (rows is None) == (markdown is None):
        raise ValueError("exactly one of 'rows' or 'markdown' must be provided")

    if markdown is not None:
        parsed = _parse_markdown_table(markdown)
        if not parsed:
            raise ValueError("no markdown table rows found in input")
        rows = parsed

    rows = [[("" if v is None else str(v)) for v in r] for r in rows or []]
    if not rows:
        raise ValueError("'rows' must contain at least one row")

    # Resolve target BEFORE creating new content (otherwise the paragraph
    # we'd just appended could be mis-counted as the anchor).
    target_el = None
    section_target: tuple[str, Any] | None = None
    if position == "after_section":
        section_target = _resolve_after_section_target(doc, anchor)
    elif position not in ("end", "start"):
        target_el = _resolve_anchor_paragraph(doc, position, anchor)

    # Suppress duplicate caption when the anchor paragraph already carries
    # identical text (e.g. caller wrote the caption via insert_text first,
    # then passed the same string here). Skipped for after_section since
    # the anchor is a heading, not a caption.
    caption_suppressed = False
    if caption and target_el is not None:
        from docx.oxml.ns import qn as _qn
        anchor_text = "".join(
            t.text or "" for t in target_el.iter(_qn("w:t"))
        ).strip()
        if anchor_text and anchor_text == caption.strip():
            caption_suppressed = True
            caption = None
    elif caption and isinstance(anchor, str) and anchor.strip() == caption.strip():
        caption_suppressed = True
        caption = None

    # Build at end (python-docx idiom) → optionally relocate.
    cap_el = None
    if caption:
        cap_para = doc.add_paragraph(caption)
        apply_cjk_font_to_para(cap_para, BODY_FONT)
        cap_el = cap_para._element

    max_cols = max(len(r) for r in rows)
    table = doc.add_table(rows=len(rows), cols=max_cols)
    table.style = "Table Grid"

    # Cell content uses ``set_cell_multiline`` so a ``\\n`` in any cell becomes
    # multiple paragraphs — otherwise the LF ends up as a literal char in
    # ``<w:t>`` and LibreOffice → PDF renders it as 乱码 (boxes / wrong glyphs).
    from .editor import set_cell_multiline

    for row_idx, row_cells in enumerate(rows):
        for col_idx in range(max_cols):
            value = row_cells[col_idx] if col_idx < len(row_cells) else ""
            cell = table.cell(row_idx, col_idx)
            set_cell_multiline(cell, value, font=BODY_FONT)

    if has_header:
        style_table(table)
    else:
        # Borders + alt shading only, no header-row styling.
        from docx.enum.table import WD_TABLE_ALIGNMENT
        from docx.oxml import OxmlElement
        from docx.oxml.ns import qn
        from .styles import (
            TABLE_ALT_ROW_COLOR,
            TABLE_BORDER_COLOR,
        )

        table.alignment = WD_TABLE_ALIGNMENT.CENTER

        def _set_cell_shading(cell, color: str) -> None:
            tc_pr = cell._element.get_or_add_tcPr()
            shading = OxmlElement("w:shd")
            shading.set(qn("w:val"), "clear")
            shading.set(qn("w:color"), "auto")
            shading.set(qn("w:fill"), color)
            tc_pr.append(shading)

        def _set_cell_borders(cell) -> None:
            tc_pr = cell._element.get_or_add_tcPr()
            borders = OxmlElement("w:tcBorders")
            for edge in ("top", "left", "bottom", "right"):
                el = OxmlElement(f"w:{edge}")
                el.set(qn("w:val"), "single")
                el.set(qn("w:sz"), "4")
                el.set(qn("w:space"), "0")
                el.set(qn("w:color"), TABLE_BORDER_COLOR)
                borders.append(el)
            tc_pr.append(borders)

        for row_idx, row in enumerate(table.rows):
            for cell in row.cells:
                _set_cell_borders(cell)
                if row_idx % 2 == 1:
                    _set_cell_shading(cell, TABLE_ALT_ROW_COLOR)
                for para in cell.paragraphs:
                    apply_cjk_font_to_para(para, BODY_FONT)

    # Vertical-merge runs of empty cells with the non-empty cell above them.
    # Without this, an LLM-authored "header row + multiple sub-rows whose
    # leading columns are blank" table renders as a fragmented mess in
    # LibreOffice → PDF (each blank cell gets its own borders + shading).
    merge_groups = 0
    if auto_merge_empty:
        merge_groups = _auto_vertical_merge_empty_cells(table, has_header)

    # Relocate caption + table together to the requested position.
    table_el = table._element
    if position == "start":
        body = list(doc.paragraphs)
        if body:
            first_el = body[0]._element
            # Order desired at top: caption?, table, ...rest. Use addprevious in
            # the order: caption, table → final order: caption, table, first…
            if cap_el is not None:
                first_el.addprevious(cap_el)
            first_el.addprevious(table_el)
    elif position in ("after_heading", "after_paragraph"):
        # Desired: target, caption?, table. Calling addnext puts each new
        # element immediately after target, so call table FIRST then caption
        # (last call wins the immediately-after-target slot).
        target_el.addnext(table_el)
        if cap_el is not None:
            target_el.addnext(cap_el)
    elif position == "after_section":
        mode, sibling_el = section_target
        if mode == "before":
            if cap_el is not None:
                sibling_el.addprevious(cap_el)
            sibling_el.addprevious(table_el)
        else:  # "at_end" — append before sectPr (or leave at body end)
            from docx.oxml.ns import qn as _qn
            sect = doc.element.body.find(_qn("w:sectPr"))
            if sect is not None:
                if cap_el is not None:
                    sect.addprevious(cap_el)
                sect.addprevious(table_el)
    elif position == "before_paragraph":
        # Desired: caption?, table, target. addprevious in order caption,
        # table → final order: caption, table, target.
        if cap_el is not None:
            target_el.addprevious(cap_el)
        target_el.addprevious(table_el)
    # else position == "end" → leave appended in place

    return {
        "row_count": len(rows),
        "column_count": max_cols,
        "has_header": has_header,
        "caption": caption,
        "caption_suppressed_duplicate": caption_suppressed,
        "position": position,
        "anchor": anchor,
        "vertical_merge_groups": merge_groups,
    }


def add_table(
    *,
    input_filename: str,
    output_filename: str,
    rows: list[list[str]] | None = None,
    markdown: str | None = None,
    has_header: bool = True,
    caption: str | None = None,
    position: str,
    anchor=None,
    auto_merge_empty: bool = True,
) -> dict[str, Any]:
    """Insert a styled table into an existing docx and save.

    Thin file-I/O wrapper around ``_add_table_to_doc`` — exposed as the
    the engine entry point that ``word_add_table`` MCP tool calls. For
    parameter semantics see ``_add_table_to_doc``. Resulting table inherits
    the report-export look (header row blue/white, alt shading, thin borders,
    CJK font everywhere) when ``has_header=True``.
    """
    from docx import Document

    doc = Document(str(input_path(input_filename)))
    sub = _add_table_to_doc(
        doc,
        rows=rows, markdown=markdown,
        has_header=has_header, caption=caption,
        position=position, anchor=anchor,
        auto_merge_empty=auto_merge_empty,
    )

    out = output_path(output_filename)
    out.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(out))

    return {"output_filename": output_filename, **sub}


def add_paragraph(
    *,
    input_filename: str,
    output_filename: str,
    text: str,
    style: str | None = None,
) -> dict[str, Any]:
    """Append a paragraph (optionally with a named style) to an existing docx."""
    from docx import Document

    doc = Document(str(input_path(input_filename)))
    para = doc.add_paragraph(text, style=style) if style else doc.add_paragraph(text)
    from .styles import BODY_FONT
    apply_cjk_font_to_para(para, BODY_FONT)

    out = output_path(output_filename)
    out.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(out))

    return {
        "output_filename": output_filename,
        "added_paragraph_chars": len(text),
        "style": style,
        "paragraph_count": len(doc.paragraphs),
    }
