"""Aggregate skill-declared dependencies into sandbox-buildable manifest files.

Reads the `dependencies` JSON column from every enabled `admin_skills` row,
merges and deduplicates per ecosystem (pip / npm / apt), then writes:

  - `<repo_root>/docker/requirements-skills.txt`   (pip)
  - `<repo_root>/docker/package-skills.json`       (npm)
  - `<repo_root>/docker/apt-skills.txt`            (apt)

These files are picked up by `docker/Dockerfile.script-runner` and
`docker/Dockerfile.opensandbox` during the rebuild flow.
"""
from __future__ import annotations

import hashlib
import json
import logging
import os
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from sqlalchemy.orm import Session

from core.db.models import AdminSkill

logger = logging.getLogger(__name__)


_PIP_HEADER = (
    "# Auto-generated by core.services.skill_deps_aggregator. DO NOT EDIT MANUALLY.\n"
    "# Managed via admin UI → 沙盒依赖 → 应用依赖。\n"
)
_NPM_DEFAULT: Dict[str, Any] = {
    "name": "hugagent-skills",
    "private": True,
    "description": "Auto-generated by skill_deps_aggregator. Do not edit manually.",
    "dependencies": {},
}
_APT_HEADER = (
    "# Auto-generated by core.services.skill_deps_aggregator. DO NOT EDIT MANUALLY.\n"
)


# ── Ignore list (deps the admin chose "do not install", persisted in SystemConfig) ───────────
# On the "sandbox deps" page the admin picks install / ignore per **uninstalled** dep; ignored
# package names are recorded here, excluded wholesale by the aggregator — they neither enter
# requirements-skills.txt (not installed on rebuild) nor appear in "uninstalled deps" anymore.
# Restoring (un-ignoring) removes it from the list, and the next rebuild picks it up again.
# Reuses the existing key-value JSON storage ContentBlock (docs_updates / skill_icons etc. all use it), zero schema change.
_IGNORE_BLOCK_ID = "sandbox_deps_ignore"
_DEP_KINDS = ("pip", "npm", "apt")


def get_ignored_deps(db: Session) -> Dict[str, List[str]]:
    """Read the ignore list {pip:[...], npm:[...], apt:[...]} (bad data tolerated as empty)."""
    from core.db.models import ContentBlock

    try:
        row = db.query(ContentBlock).filter(ContentBlock.id == _IGNORE_BLOCK_ID).first()
        data = row.payload if (row and isinstance(row.payload, dict)) else {}
    except Exception:  # noqa: BLE001
        data = {}
    return {k: list(data.get(k) or []) for k in _DEP_KINDS}


def set_ignored_deps(db: Session, ignored: Dict[str, List[str]]) -> Dict[str, List[str]]:
    """Replace the ignore list wholesale (dedup, drop empties, sort by name) and persist to ContentBlock."""
    from sqlalchemy.orm.attributes import flag_modified

    from core.db.models import ContentBlock

    clean = {
        k: sorted({str(n).strip() for n in (ignored.get(k) or []) if str(n).strip()}, key=str.lower)
        for k in _DEP_KINDS
    }
    row = db.query(ContentBlock).filter(ContentBlock.id == _IGNORE_BLOCK_ID).first()
    if row is not None:
        row.payload = clean
        flag_modified(row, "payload")
    else:
        db.add(ContentBlock(id=_IGNORE_BLOCK_ID, payload=clean))
    db.commit()
    return clean


def _collect(
    db: Session, kind: str, *, ignored: Optional[Dict[str, List[str]]] = None
) -> Dict[str, Optional[str]]:
    """Walk enabled admin skills and merge `dependencies[kind]` into a {name: version}.

    Manual-source pins override others.  When two skills pin different versions of
    the same package, the longer constraint string wins (a crude proxy for "more
    specific"). Packages in the admin ignore list are excluded wholesale (not in the manifest,
    not counted in installed/missing statistics).
    ``ignored`` can be pre-read once by the caller and passed in, to avoid repeatedly reading
    ContentBlock multiple times within a single request.
    """
    if ignored is None:
        ignored = get_ignored_deps(db)
    ignored_set = {n.lower() for n in ignored.get(kind, [])}
    rows = db.query(AdminSkill).filter(AdminSkill.is_enabled.is_(True)).all()
    out: Dict[str, Tuple[Optional[str], str]] = {}  # name -> (version, source)
    for r in rows:
        deps = r.dependencies or {}
        entries = deps.get(kind) or []
        for entry in entries:
            name = (entry.get("name") or "").strip()
            if not name or name.lower() in ignored_set:
                continue
            ver = (entry.get("version") or None)
            src = entry.get("source") or "static_scan"
            cur = out.get(name)
            if cur is None:
                out[name] = (ver, src)
                continue
            cur_ver, cur_src = cur
            # Manual always wins.
            if src == "manual" and cur_src != "manual":
                out[name] = (ver, src)
                continue
            if cur_src == "manual" and src != "manual":
                continue
            # Pick the more specific constraint (longer pin string) if conflict.
            if ver and (not cur_ver or len(ver) > len(cur_ver)):
                out[name] = (ver, src)
    return {name: ver for name, (ver, _src) in out.items()}


def aggregate_names(db: Session) -> Dict[str, List[str]]:
    """Aggregate the dependency **package names** (without versions) of all enabled skills, for "sandbox installed" detection."""
    ignored = get_ignored_deps(db)
    return {
        kind: sorted(_collect(db, kind, ignored=ignored).keys(), key=str.lower)
        for kind in _DEP_KINDS
    }


def _render_pip(merged: Dict[str, Optional[str]]) -> str:
    """Render `requirements-skills.txt` body from a merged {name: version} map."""
    lines = [_PIP_HEADER]
    for name in sorted(merged, key=str.lower):
        ver = merged[name]
        if ver:
            # Pass through pip-compatible constraints; the column also stores
            # poetry's `^1.2` / `~1.2`, which pip rejects — strip those.
            ver_s = ver.strip()
            if ver_s.startswith("^") or ver_s.startswith("~"):
                lines.append(f"{name}\n")
            else:
                # Allow bare versions to imply >= for ergonomics
                if ver_s and ver_s[0].isdigit():
                    ver_s = ">=" + ver_s
                lines.append(f"{name}{ver_s}\n")
        else:
            lines.append(f"{name}\n")
    return "".join(lines)


def _render_npm(merged: Dict[str, Optional[str]]) -> str:
    """Render `package-skills.json` body from a merged {name: version} map."""
    payload = dict(_NPM_DEFAULT)
    payload["dependencies"] = {
        name: (merged[name] or "*") for name in sorted(merged, key=str.lower)
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def _render_apt(merged: Dict[str, Optional[str]]) -> str:
    """Render `apt-skills.txt` body from a merged {name: version} map."""
    return "".join([_APT_HEADER, *(f"{name}\n" for name in sorted(merged, key=str.lower))])


def render_pip_requirements(db: Session) -> str:
    """Return the body of `requirements-skills.txt`."""
    return _render_pip(_collect(db, "pip"))


def render_npm_package_json(db: Session) -> str:
    """Return the body of `package-skills.json`."""
    return _render_npm(_collect(db, "npm"))


def render_apt_packages(db: Session) -> str:
    """Return the body of `apt-skills.txt`."""
    return _render_apt(_collect(db, "apt"))


def aggregate_all(db: Session) -> Dict[str, Any]:
    """Compute all three manifest bodies + names + a stable hash, without touching disk.

    Collects each ecosystem **once** (sharing a single ignore-list read), so callers
    that also need package names (the preview endpoint) needn't re-aggregate.
    """
    ignored = get_ignored_deps(db)
    merged = {kind: _collect(db, kind, ignored=ignored) for kind in _DEP_KINDS}
    pip, npm, apt = _render_pip(merged["pip"]), _render_npm(merged["npm"]), _render_apt(merged["apt"])
    hasher = hashlib.sha256()
    hasher.update(pip.encode("utf-8"))
    hasher.update(b"\x00")
    hasher.update(npm.encode("utf-8"))
    hasher.update(b"\x00")
    hasher.update(apt.encode("utf-8"))
    return {
        "pip": pip,
        "npm": npm,
        "apt": apt,
        "hash": hasher.hexdigest(),
        "names": {kind: sorted(merged[kind].keys(), key=str.lower) for kind in _DEP_KINDS},
        "ignored": ignored,
    }


def write_manifests(
    db: Session,
    repo_root: str = "/app/repo",
) -> Dict[str, Any]:
    """Render manifests and write them to the build context. Returns {hash, paths, changed}."""
    bundle = aggregate_all(db)
    root = Path(repo_root)
    if not root.is_dir():
        raise FileNotFoundError(f"repo_root not found: {repo_root}")

    targets = {
        "pip": root / "docker" / "requirements-skills.txt",
        "npm": root / "docker" / "package-skills.json",
        "apt": root / "docker" / "apt-skills.txt",
    }
    changed: List[str] = []
    for kind, path in targets.items():
        content = bundle[kind]
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old != content:
            path.write_text(content, encoding="utf-8")
            changed.append(str(path.relative_to(root)))

    logger.info(
        "skill_deps_manifests_written: hash=%s changed=%s",
        bundle["hash"][:12],
        changed,
    )
    return {
        "hash": bundle["hash"],
        "paths": {k: str(v.relative_to(root)) for k, v in targets.items()},
        "changed": changed,
    }


def get_repo_root() -> str:
    """Resolve the build-context root.

    Priority:
      1. HOST_REPO_PATH (set in .env to the host absolute path; container
         mounts itself at the same path so docker daemon sees the right files)
      2. REPO_ROOT (legacy override)
      3. /app/repo (back-compat mount)
      4. cwd
    """
    for var in ("HOST_REPO_PATH", "REPO_ROOT"):
        v = os.environ.get(var)
        if v and Path(v).is_dir():
            return v
    if Path("/app/repo").is_dir():
        return "/app/repo"
    return os.getcwd()
